# Generated by Django 5.1.4 on 2025-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('picture1', models.ImageField(upload_to='user_pictures/')),
                ('picture2', models.ImageField(upload_to='user_pictures/')),
                ('picture3', models.ImageField(upload_to='user_pictures/')),
                ('picture4', models.ImageField(upload_to='user_pictures/')),
            ],
        ),
    ]
